<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use App\Models\CaseModel;
use App\Models\Signature;
use Illuminate\Http\Request;
use App\Models\CaseQuestions;
use Illuminate\Support\Facades\DB;
use App\Models\LegalRepresentation;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\HttpFoundation\RedirectResponse;

class ClientController extends Controller
{
    public function index()
    {
        return Inertia::render('Client/Index');
    }

    public function ViewLegalNeedForm()
    {
        return Inertia::render('Client/CreateLegalNeed');
    }


    public function AddLegalNeed(Request $request): RedirectResponse
    {
        $userId = Auth::id();
        // dd($request->all());
        // Retrieve all form fields from the request
        // Define validation rules for all form fields
        $request->validate ([
            'DateOfNextAppearance' => ['required', 'date', 'after_or_equal:today'],
            'NatureOfAppearance' => ['required', 'string'],
            'ServicesLanguage' => ['nullable', 'string'],
            'AdditionalInformation' => ['nullable', 'string'],
            'Question1' => ['required', 'string'],
            'Question2' => ['nullable', 'string'],
            'Question3' => ['nullable', 'string'],
            'ReasonForChange' => ['nullable', 'string'],
            'Signature' => ['required', 'string'],
            'PrintName' => ['required', 'string'],
            'SignDate' => ['required', 'date'],
        ]);

        // $formFields = $request->only([
        //     'DateOfNextAppearance',
        //     'NatureOfAppearance',
        //     'ServicesLanguage',
        //     'AdditionalInformation',
        //     'Question1',
        //     'Question2',
        //     'Question3',
        //     'ReasonForChange',
        //     'Signature',
        //     'PrintName',
        //     'SignDate',
        // ]);


        // Create the case model
        $case = CaseModel::create([
            'id' => $userId,
            'DateOfNextAppearance' => $request->DateOfNextAppearance,
            'NatureOfAppearance' => $request->NatureOfAppearance,
            'ServicesLanguage' => $request->ServicesLanguage,
            'AdditionalInformation' => $request->AdditionalInformation,
        ]);

        // Check if case model was successfully created
        if (!$case) {
            // return redirect('/')->with('error', 'Failed to create CaseModel.');
        }

        // Fetch the CaseID generated by the database
        $caseID = $case->id;

        // Create case questions
        $caseQuestions = CaseQuestions::create([
            'CaseID' => $caseID,
            'Question1' => $request->Question1,
            'Question2' => $request->Question2,
            'Question3' => $request->Question3,
        ]);

        // Associate case questions with the case
        $case->caseQuestions()->save($caseQuestions);

        // Create legal representation
        $legalRepresentation = LegalRepresentation::create([
            'CaseID' => $caseID,
            'ReasonForChange' => $request->ReasonForChange,
        ]);

        // Check if legal representation was successfully created
        if (!$legalRepresentation) {
            // Rollback the case creation and associated case questions
            $case->caseQuestions()->delete();
            $case->delete();

            // return redirect('/')->with('error', 'Failed to create LegalRepresentation.');
        }

        // Create signature
        $signature = Signature::create([
            'CaseID' => $caseID,
            'Signature' => $request->Signature,
            'PrintName' => $request->PrintName,
            'SignDate' => $request->SignDate,
        ]);

        // Check if signature was successfully created
        if (!$signature) {
            // Rollback the case creation, associated case questions, and legal representation
            $case->caseQuestions()->delete();
            $case->delete();
            $legalRepresentation->delete();

            // return redirect('/')->with('error', 'Failed to create Signature.');
        }

        // Optionally, you can return a response indicating success
        return redirect(route('dashboard', absolute: false));
    }
}
